#!/bin/bash
docker build -t lsikidi/express-user-referential-crud-api .
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push lsikidi/express-user-referential-crud-api