---
- hosts: all
  gather_facts: yes
  vars_files:
    - vars/vars.yml
    - vars/db.yml

  pre_tasks:
    - name: Add archive.ubuntu.com repository
      become: yes
      apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu trusty universe
        state: present
    - name: Update apt cache if needed.
      become: yes
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - name: geerlingguy.postgresql
      become: yes
    - name: geerlingguy.nodejs
      become: yes
  
  tasks:
  - name: Disable the firewall (since this is for local dev only).
    become: yes
    service: name=ufw state=stopped

  - name: Ensure Node.js app folder exists.
    file: path={{ node_application_location }} state=directory

  - name: Install app dependencies defined in package.json.
    npm: path={{ node_application_location }}

  - name: Add .env in the project's root folder 
    template:
      src: "templates/local.dotenv.j2"
      dest: "{{ node_application_location }}/.env"
      owner: ubuntu
      group: ubuntu
      mode: 0644

  - name: Check list of running Node.js apps.
    command: /usr/local/lib/npm/bin/pm2 list
    become_user: "{{ ansible_user }}"
    register: pm2_list
    changed_when: false

  - name: Start the application.
    command: "/usr/local/lib/npm/bin/pm2 start npm --name {{ api_service_name }} -- start"
    args:
      chdir: "{{ node_application_location }}"
    become_user: "{{ ansible_user }}"
    when: pm2_list.stdout.find(api_service_name) == -1